sudo: required
install: true

services:
  - docker

language: node_js
node_js:
  - "node"

script:
  - docker build -t davidkassa/dotnet-nodejs .
  - docker run davidkassa/dotnet-nodejs /bin/sh -c "dotnet --version;node --version;npm --version"
